const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
const X='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',Y='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
test('PostgreSQL enforces membership, atomic claims, owner checks, limits and reset leases',async()=>{
 const db=new PGlite();
 try {
  await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE ROLE service_role;
   CREATE TABLE users(id uuid PRIMARY KEY,middleauth_email text);
   CREATE TABLE admins(email text);
   CREATE TABLE proofreading_tasks(id serial PRIMARY KEY,segment_id text,dataset text,status text DEFAULT 'pending',assigned_to uuid,claim_point_x double precision,claim_point_y double precision,claim_point_z double precision,supervoxel_id text,final_segment_id text,soma_coords text,updated_at timestamptz DEFAULT now());
   CREATE TABLE task_assignments(id serial PRIMARY KEY,task_id integer,user_id uuid,status text DEFAULT 'active',expires_at timestamptz,released_at timestamptz,completed_at timestamptz);
   CREATE TABLE tutorial_practice_examples(id uuid PRIMARY KEY,title text,kind text,dataset text,pcg_server text,pcg_table text,supervoxel_a text,supervoxel_b text,root_a text,root_b text,status text DEFAULT 'ready',enabled boolean DEFAULT true,claimed_by uuid,claimed_at timestamptz,expires_at timestamptz,uses integer DEFAULT 0,created_at timestamptz DEFAULT now(),updated_at timestamptz DEFAULT now(),last_error text,last_reset_at timestamptz,reset_failures integer DEFAULT 0);
   INSERT INTO users VALUES('${A}','a@example.invalid'),('${B}','b@example.invalid'),('${C}','outside@example.invalid');
   INSERT INTO admins VALUES('a@example.invalid');
   INSERT INTO proofreading_tasks(segment_id,dataset) VALUES('123','pinky_nf_v2');
   INSERT INTO tutorial_practice_examples(id,kind,dataset,pcg_server,pcg_table,supervoxel_a,supervoxel_b,root_a,root_b) VALUES('${X}','cut','pinky_nf_v2','https://minnie.microns-daf.com','pinky_nf_v2','10','20','100','200'),('${Y}','merge_then_cut','pinky_nf_v2','https://minnie.microns-daf.com','pinky_nf_v2','20','30','200','300');`);
  await db.exec(fs.readFileSync(path.join(__dirname,'../supabase-pilot-access.sql'),'utf8'));
  await db.exec(fs.readFileSync(path.join(__dirname,'../supabase-practice-overlap-guard.sql'),'utf8'));
  const call=async(fn,user,action,args)=> (await db.query('SELECT public.'+fn+'($1,$2,$3::jsonb) AS result',[user,action,JSON.stringify(args)])).rows[0].result;
  const task=(user,action,args)=>call('pilot_task_action',user,action,args);
  const practice=(user,action,args)=>call('pilot_practice_action',user,action,args);
  await db.exec("INSERT INTO pilot_members(email) VALUES('b@example.invalid')");
  await assert.rejects(()=>task(C,'claim',{id:1}),/Invited testers only/);
  const competing=await Promise.allSettled([task(A,'claim',{id:1}),task(B,'claim',{id:1})]);
  assert.equal(competing.filter(r=>r.status==='fulfilled').length,1);
  assert.equal((await db.query('SELECT count(*)::integer AS n FROM task_assignments')).rows[0].n,1);
  await assert.rejects(()=>task(B,'release',{id:1}),/current owner/);
  await task(A,'claim',{id:1});
  assert.equal((await db.query('SELECT count(*)::integer AS n FROM task_assignments')).rows[0].n,1);
  await assert.rejects(()=>task(B,'claim_cell',{dataset:'pinky_nf_v2',segment_id:'123',point:[1,2,3]}),/already claimed/);
  // Claim limit is 8 (Amy 2026-09-28): A already holds task 1, so 7 more fit.
  for (let i=0;i<7;i++) await task(A,'claim_cell',{dataset:'pinky_nf_v2',segment_id:String(124+i),point:[2+i,2,3]});
  await assert.rejects(()=>task(A,'claim_cell',{dataset:'pinky_nf_v2',segment_id:'131',point:[9,2,3]}),/Max 8/);
  assert.equal((await db.query('SELECT count(*)::integer AS n FROM proofreading_tasks')).rows[0].n,8);
  await task(A,'release',{id:1}); await task(B,'claim',{id:1});
  // Each claim keeps its own saved view: owner only, https only (2026-09-28).
  await task(B,'save_link',{id:1,link:'https://spelunker.cave-explorer.org/#!middleauth+https://x.test/1'});
  assert.equal((await db.query('SELECT working_link FROM proofreading_tasks WHERE id=1')).rows[0].working_link,'https://spelunker.cave-explorer.org/#!middleauth+https://x.test/1');
  await assert.rejects(()=>task(A,'save_link',{id:1,link:'https://x.test/2'}),/current owner/);
  for (const bad of ['http://x.test','javascript:alert(1)','https://a b','']) await assert.rejects(()=>task(B,'save_link',{id:1,link:bad}),/https link/);
  await db.exec("UPDATE task_assignments SET status='expired',expires_at=now()-interval '1 minute' WHERE task_id=1 AND user_id='"+A+"'; SELECT expire_stale_assignments();");
  assert.equal((await db.query('SELECT assigned_to FROM proofreading_tasks WHERE id=1')).rows[0].assigned_to,B);
  const held=await practice(A,'claim',{kind:'cut'});assert.equal(held.id,X);
  assert.equal(await practice(A,'claim',{kind:'cut',exclude:[X]}),null);
  assert.equal((await practice(A,'claim',{kind:'cut'})).claim_nonce,held.claim_nonce);
  assert.equal(await practice(B,'claim',{kind:'merge_then_cut'}),null);
  await assert.rejects(()=>practice(B,'begin_reset',{id:X}),/no longer yours/);
  await assert.rejects(()=>practice(A,'begin_reset',{id:X,session:Y}),/no longer yours/);
  await assert.rejects(()=>practice(A,'heartbeat',{id:X,session:Y}),/session has ended/);
  const reset=await practice(A,'begin_reset',{id:X,session:held.claim_nonce});assert.ok(reset.reset_nonce);
  await assert.rejects(()=>practice(A,'begin_reset',{id:X}),/already running/);
  await assert.rejects(()=>practice(B,'check_reset',{id:X,nonce:reset.reset_nonce}),/lease has ended/);
  await assert.rejects(()=>practice(A,'finish_reset',{id:X,nonce:Y,clean:true}),/lease has ended/);
  await practice(A,'check_reset',{id:X,nonce:reset.reset_nonce});
  await practice(A,'finish_reset',{id:X,nonce:reset.reset_nonce,clean:true,root_a:'999',root_b:'998'});
  assert.equal((await db.query('SELECT root_a FROM tutorial_practice_examples WHERE id=$1',[X])).rows[0].root_a,'100');
  assert.equal((await practice(B,'claim',{kind:'merge_then_cut'})).id,Y);
  await assert.rejects(()=>practice(A,'check_reset',{id:X,nonce:reset.reset_nonce}),/lease has ended/);
  await assert.rejects(()=>practice(A,'begin_reset',{id:Y}),/no longer yours/);
  await db.exec("UPDATE tutorial_practice_examples SET expires_at=now()-interval '1 second' WHERE id='"+Y+"'");
  assert.equal(await practice(B,'claim',{kind:'merge_then_cut'}),null);
  assert.equal((await db.query('SELECT status FROM tutorial_practice_examples WHERE id=$1',[Y])).rows[0].status,'needs_reset');
  const pending=(await db.query('SELECT updated_at::text FROM tutorial_practice_examples WHERE id=$1',[Y])).rows[0].updated_at;
  const worker=(await db.query('SELECT pilot_worker_reset_lease($1,$2) AS result',[Y,pending])).rows[0].result;
  assert.ok(worker.reset_nonce);
  await assert.rejects(()=>practice(B,'begin_reset',{id:Y}),/already running/);
  assert.equal((await db.query('SELECT pilot_worker_reset_lease($1,$2) AS result',[Y,pending])).rows[0].result,null);
  await db.exec(fs.readFileSync(path.join(__dirname,'../supabase-pilot-lockdown.sql'),'utf8'));
  assert.equal((await db.query("SELECT has_function_privilege('anon','pilot_task_action(uuid,text,jsonb)','EXECUTE') AS allowed")).rows[0].allowed,false);
  assert.equal((await db.query("SELECT has_function_privilege('service_role','pilot_task_action(uuid,text,jsonb)','EXECUTE') AS allowed")).rows[0].allowed,true);
 } finally {await db.close();}
});
